# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Export
      run: yarn export

    - name: Nojekyll file
      run: touch ./out/.nojekyll

    - name: Verify cache
      run: npm cache verify

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      env: 
        NEXT_PUBLIC_GTM_ID: ${{secrets.NEXT_PUBLIC_GTM_ID}}
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: out # The folder the action should deploy.
